### ISSUE TITLE
Feature request: Choose which element do display/hide

### ISSUE THREAD

**Issue by nicop4** [royto/logbook-card#1]
Hi, 

This is a nice card, I already added it to my system ;)

Some improvement ideas:
Let the user choose which element is displayed/hidden, for instance when only one value is monitored, the value itself is not really important and could be hidden.
With that, being able to select date/time format, and display only start date as we already have the duration.

A configuration like below could be used:

```yaml
show:
  - start_date: true
  - end_date: false
  - value: true
  - duration: true
```

Thanks for your awesome work 👍
