### ISSUE TITLE
State dependant icons (motion, door / window sensors / locks / alarms) replaced with mdi:bookmark

### ISSUE THREAD

**Issue by Mincka** [royto/logbook-card#103]
**Describe the bug**
Home Assistant has new requirements for icons starting with 2024.2.0.
State dependant icons (motion, door / window sensors / locks / alarms) replaced with mdi:bookmark

Same as described here: https://github.com/benct/lovelace-multiple-entity-row/issues/330

**To Reproduce**
Show log events with icons for a door or window.

**Expected behavior**
Show the door, or window instead of the bookmark.

**Screenshots**
![image](https://github.com/royto/logbook-card/assets/6184289/33807cd0-4d61-4c97-815e-4b8cdabdb902)

**Environment (please complete the following information):**
 - HA Version: 2024.2
 - Browser Edge
 - Card version 2.3.0

**Card configuration**
```
type: custom:logbook-card
title: Porte d'entrée
entity: binary_sensor.porte_d_entree
show:
  end_date: false
  start_date: true
  duration: false
  icon: true
scroll: true
date_format: DD/MM/YYYY HH:mm
no_event: La porte n'a pas été ouverte dans les 2 dernières heures.
hidden_state:
  - unavailable
  - 'off'
collapse: 4
history: 1
```

**Additional context**
You can have a look at this PR for the fix: https://github.com/benct/lovelace-multiple-entity-row/pull/331
