### ISSUE TITLE
Labels do not work in custom:multiple-logbook-card

### ISSUE THREAD

**Issue by cicero200272** [royto/logbook-card#104]
**Describe the bug**
When using custom:multiple-logbook-card, labels in state_map do not work. 

**To Reproduce**
1. Create a custom:multiple-logbook-card
2. Add state_map to the config
3. Add a label to the state_map config

**Expected behavior**
History entries in the card use the label as configured.

**Screenshots**
![image](https://github.com/royto/logbook-card/assets/15817602/4789e622-64a5-4e51-a0ad-4577f150e9a1)

Correct behaviour in custom:logbook-card:
![image](https://github.com/royto/logbook-card/assets/15817602/d0ee949a-e5e1-49e0-8055-368b1f01b8e2)

**Environment (please complete the following information):**
 - HA Version: 2024.2.1
 - Browser Chrome
 - Card version 2.4.0

**Card configuration**
```
- type: custom:multiple-logbook-card
  title: []
  collapse: 5
  group_by_day: true
  date_format: "HH:mm"
  show:
    end_date: false
    duration: false
    state: false
  entities:
    - entity: binary_sensor.turklingel
      hidden_state: ["on", "unavailable"]
      state_map:
        - value: "*"
          label: []
          icon: mdi:alarm-bell
      custom_logs: true
      custom_log_map:
        - name: "*"
          icon: mdi:door-open
          icon_color: var(--state-icon-color)
```

**Comment by royto** [comment]
In multiple `multiple-logbook-card`, the name of the entity is displayed before the state

use `entity_name` show option to hide it

```yaml
show:
    end_date: false
    duration: false
    state: false
    entity_name: false
```
