### ISSUE TITLE
error date

### ISSUE THREAD

**Issue by NJPYY** [royto/logbook-card#107]
**Describe the bug**
The start and end times displayed on the card are inconsistent with HA's own history
![WechatIMG3731](https://github.com/royto/logbook-card/assets/138848548/1f4f2868-c5bb-4da1-8068-3e17fb134167)

![WechatIMG3729](https://github.com/royto/logbook-card/assets/138848548/60594ad4-04e8-4cc9-8ef1-20412f86ca38)

**Comment by royto** [comment]
Hello, do you have a user time settings like in #101 ?

**Comment by NJPYY** [comment]
> Hello, do you have a user time settings like in #101 ?

No, but it doesn't seem to be a time zone issue, as the time difference is over 20 days

**Comment by NJPYY** [comment]
All time displays in HA are correct, only this card is incorrect

**Comment by royto** [comment]
Are you using a custom date format?
Can you paste the configuration of the card ?

**Comment by NJPYY** [comment]
```
cards:
  - type: grid
    view_layout:
      grid-area: alarm
    square: false
    columns: 1
    cards:
      # 告警记录
      - type: custom:logbook-card
        desc: true
        entity: input_text.wen_du_chuan_gan_qi_zi_yan_gao_jing_wen_ben
        scroll: true
        date_format: YYYY-MM-dd hh:mm:ss
        hidden_state:
          - ok
          - 未知
          - None
          - unavailable
        title: 告警记录
        history: 180
        max_items: 500
        no_event: 暂无告警
        show:
          state: true
          duration: false
          start_date: true
          end_date: false
          icon: false
          separator: false
          entity_name: true
        card_mod:
          style: |
            .card-content-scroll {
                max-height: 76vh !important;
            }
```
