### ISSUE TITLE
Add hidden_state function to Multiple entities Logbook Card

### ISSUE THREAD

**Issue by yangrusen** [royto/logbook-card#110]
I saw hidden_state in the Logbook Card and had tested it successfully. Now, I would like to apply it in the Multiple entities Logbook Card, but unfortunately, it does not seem to have this feature. Is it possible to add it to the Multiple entities Logbook Card as well? Thank you!

**Comment by royto** [comment]
It is supported. You can confiured it per entities

```
title: Sun and Moon phase
entities:
  - entity: sun.sun
    custom_logs: true
    hidden_state: 
      - 'above_horizon' 
  - entity: sensor.moon_phase
type: custom:multiple-logbook-card
````
