### ISSUE TITLE
After version 2.5.1, cards with attributes are empty

### ISSUE THREAD

**Issue by kosmaluk** [royto/logbook-card#113]
- HA Version: [e.g. 2024.3.1]
 - Browser chrome, HA apps
 - Card version [e.g. 2.5.1]

**Card configuration**
```yaml
type: custom:logbook-card
show:
  end_date: false
  start_date: true
  separator: true
  duration: true
separator_style:
  color: '#3D3D3B'
entity:
  - sensor.notify_last_redmi_all_attr
title: ''
attributes:
  - value: Tytul
    label: Tytuł:-
    type: text
  - value: Tresc
    label: Treść:-
    type: text
  - value: TextLines
    label: Line:-
    type: text
  - value: Messages
    label: Mess:-
    type: text
custom_logs: true
no_event: Brak
hours_to_show: 24
collapse: 0
```

After updating to version 2.5.1, all items stopped being displayed in some tabs (they are empty).
After analyzing the problem, I found out that it was caused by a change in version 2.5.1. I don't know exactly what it is about, but it concerns attributes. Some cards display attributes and some do not. Those that do not display often have "empty" or "null" attributes. Adding one such attribute that has the value "empty" or "null" in the history causes the card to display nothing.
If I remove the entire "attributes" section, the card displays correctly, i.e. it shows the entity states (without attributes)

This is card correctly (wer 2.5.0)
![IMG20240318124023](https://github.com/royto/logbook-card/assets/126351906/d265a88f-3408-4489-9a2a-4100e67c5062)

This is card afrer ver 2.5.1
![IMG20240318124206](https://github.com/royto/logbook-card/assets/126351906/95c79bcf-6c23-48e0-b13b-9733c0d8527a)

This is card after remove "attribute" section
![IMG20240318124246](https://github.com/royto/logbook-card/assets/126351906/ed08024a-34aa-454f-adb0-f775caf0c6d6)
