### ISSUE TITLE
Panel view full height

### ISSUE THREAD

**Issue by ech58** [royto/logbook-card#114]
Hello Julien,

I' m trying to display the custom logbook-card in a panel (1 card) but the card does not fit the full height of the panel.

I see [here](https://community.home-assistant.io/t/card-mod-add-css-styles-to-any-lovelace-card/120744/3946) that this is a know problem with the standard logbook card and that a workaround is to add :

```
card_mod:
  style: |
    ha-logbook {
      height: calc(100vh - var(--header-height) - 32px) !important;
    }
``` 

Is there something equivalent to ha-logbook I could use to apply this code to the custom logbook-card ?

Eric

**Comment by royto** [comment]
Hello, 

can you try adding this custom style:

```yaml
card_mod:
  style: |
    ha-card {
      height: calc(100vh - var(--header-height) - 32px) !important;
    }
    ha-card .card-content-scroll {
      height: 100%;
      max-height: 100%;
    }
```
