### ISSUE TITLE
Styling based on the value of an attribute ?

### ISSUE THREAD

**Issue by ech58** [royto/logbook-card#115]
Hello,

Do you think it is possible to change the style (with card-mod) of an attribute, based on its value (in each logbook line) ?

Eric

**Comment by royto** [comment]
Duplicate of #106 no ?

**Comment by ech58** [comment]
Hello,
Just FYI ...
My goal was to differentiate a line of the logbook from another line by changing the color, depending on the value of the attribute "type" :
if type = "info" then green
if type = "alarme" then red

I succeed to do that with

```
    state_map:
      - value: '*'
        icon: mdi:bell
        icon_color: DarkRed
        attributes:
          - name: type
            value: alarme
      - value: '*'
        attributes:
          - name: type
            value: info
        icon: mdi:information
        icon_color: DarkGreen
```
