### ISSUE TITLE
Remove duplicates in multiple logbook card

### ISSUE THREAD

**Issue by Kanecaine** [royto/logbook-card#116]
**Describe the bug**
The feature described here

https://github.com/royto/logbook-card/issues/8#issue-517587134

doesnt work in multiple logbook card. I wanted to see a logbook for my window sensors and want to show when they have been open.

**Expected behavior**
No duplicate entries.

**Screenshots**
![IMG_0433](https://github.com/royto/logbook-card/assets/99053167/27297bbf-fc59-4ab4-aaaf-2342e57e8695)

**Environment (please complete the following information):**
 - HA Version: 2024.3.3
 - Browser: Safari, iPad, latest iOS
 - Card version: 2.5.5

**Card configuration**
```yaml

type: custom:multiple-logbook-card
desc: true
entities:
  - entity: binary_sensor.alle_fenster
    hidden_state:
      - unavailable
      - 'on'
    state_map:
      - label: geschlossen
        value: 'off'
  - entity: binary_sensor.fenster_bad
    hidden_state:
      - unavailable
      - 'off'
    state_map:
      - label: geöffnet
        value: 'on'
  - entity: binary_sensor.terrassentur
    hidden_state:
      - unavailable
      - 'off'
    state_map:
      - label: geöffnet
        value: 'on'
  - entity: binary_sensor.fenster_wohnen_links
    hidden_state:
      - unavailable
      - 'off'
    state_map:
      - label: geöffnet
        value: 'on'
title: Fenster
collapse: 1
show:
  end_date: false
  start_date: true
group_by_day: true
scroll: true
minimal_duration: 90
``` 

**Additional context**
I used the logbook card for multiple entities and added each window sensor with a state filter for „unavailable“ and „off“ - for showing only when they are open. Additionally i added a „all windows closed“ sensor with a state filter for „on“ - for showing only when all windows are closed. I turned on the group-by-day function.
