### ISSUE TITLE
Increase height of card

### ISSUE THREAD

**Issue by 1darklyte** [royto/logbook-card#123]
Hello

I see the note in the instructions on how to increase the height of the card in panel mode. However I am attempting to increase the height of the logbook (with scroll enabled) for the card while not in panel mode

I attempted the below cardmod code without any change.

```
card_mod:
  style: |
    ha-card {
      height: 500px !important;
    }
```

Appreciate your help on this

**Comment by royto** [comment]
Hello @1darklyte 

try with 
```css
card_mod:
  style: |
    ha-card .card-content-scroll {
      height: 500px;
      max-height: 100%;
    }
```

**Comment by 1darklyte** [comment]
Thank you for the assistance.

It didn't work, but i also realize I'm combining Auto Entities and Multiple Logbook to get wildcard filtering for the logbook which makes it more complex

Full card below

```
type: custom:auto-entities
card:
  type: custom:multiple-logbook-card
  desc: true
  group_by_day: true
  scroll: true
  history: 3
  show:
    separator: true
    state: true
    duration: false
    start_date: false
    end_date: true
    icon: true
    entity_name: true
  card_param: entities
filter:
  include:
    - entity_id: light.*
    - entity_id: climate.*
    - entity_id: fan.*
    - entity_id: person.*
  exclude:
    - entity_id: light.door
  card_mod:
    style: |
      ha-card .card-content-scroll {
        height: 500px;
        max-height: 100%;
      }
```

**Comment by royto** [comment]
You  need to put the card mod config inside the card config like this:

```yaml
type: custom:auto-entities
card:
  type: custom:multiple-logbook-card
  desc: true
  group_by_day: true
  scroll: true
  history: 3
  show:
    separator: true
    state: true
    duration: false
    start_date: false
    end_date: true
    icon: true
    entity_name: true
  card_mod:
    style: |
      ha-card .card-content-scroll {
        height: 500px;
        max-height: 100%;
      }
  card_param: entities
filter:
  include:
    - entity_id: light.*
    - entity_id: climate.*
    - entity_id: fan.*
    - entity_id: person.*
  exclude:
    - entity_id: light.tc_helicon_goxlrmini*
    - entity_id: light.bedroom*
    - entity_id: light.hallway
    - entity_id: light.door
sort:
  method: last_updated
  reverse: true
```

**Comment by 1darklyte** [comment]
thank you thank you thank you thank you that worked

Is there a way to do wildcard filtering in logbook card by chance. Would love to ditch the auto entities part.

**Comment by royto** [comment]
There is a [feature request](https://github.com/royto/logbook-card/issues/77) about this. 
I'm closing the issue

**Comment by AJolly** [comment]
For anyone finding this comment wanting to do this with the normal logbook:
```

type: custom:config-template-card
entities:
  - input_text.label
variables:
  - states['input_text.label'].state
card:
  type: custom:auto-entities
  filter:
    include:
      - options: {}
        label: ${vars[0]}
    exclude:
      - options: {}
        state: unavailable
      - options: {}
        state: unknown
      - options: {}
        label: excludeme
    sort:
      method: state
      numeric: true
      reverse: true
    show_empty: false
    unique: true
  card:
    type: logbook
    title: ${`Entities no unavailable (${vars[0]})`}
    card_mod:
      style: |
        ha-logbook {
          height: 800px !important;
          max-height: 100% important;
        }

```
