### ISSUE TITLE
Custom logged events does not shows

### ISSUE THREAD

**Issue by wavelov3r** [royto/logbook-card#125]
Event:

`service: logbook.log
data:
  name: Relay numero 7
  entity_id: switch.accesscontroller_relay_7
  message: E' stato aperto da  {{utente}}
  domain: switch
enabled: true`

custom-logbook-card:

`type: custom:multiple-logbook-card
desc: true
entities:
  - entity: switch.gar_accesscontroller_relay_7
    hidden_state:
      - unavailable
    state_map:
      - label: aperto
        value: 'on'
      - label: chiuso
        value: 'off'
group_by_day: true
show:
  end_date: false
  start_date: true`

Result:

![image](https://github.com/royto/logbook-card/assets/104383649/e629c292-670e-4765-919f-49f3098f63b0)

But in the main logbook:

![image](https://github.com/royto/logbook-card/assets/104383649/4a5900dc-2747-4f22-93b2-a2b1a561f4ad)

**Comment by royto** [comment]
Try to add `custom_logs: true` in your entity

```yaml
type: custom:multiple-logbook-card
desc: true
entities:
  - entity: switch.accesscontroller_relay_7
    custom_logs: true
    hidden_state:
      - unavailable
    state_map:
      - label: aperto
        value: 'on'
      - label: chiuso
        value: 'off'
group_by_day: true
show:
  end_date: false
  start_date: true
```
