### ISSUE TITLE
Multiple Logbook Card with auto-entities error

### ISSUE THREAD

**Issue by clau-bucur** [royto/logbook-card#128]
**Describe the bug**
I'm unable to combine `multiple-logbook-card` with `auto-entities` and I get the following error in the console: `card custom:multiple-logbook-card Error: Please define at least one entity in entities`.

Here's a sample of the code I've tried:
```
type: custom:auto-entities
card:
  type: custom:multiple-logbook-card
filter:
  include:
    - group: group.motion_area_living
```
Tried with other examples too, even with the complete code from https://github.com/royto/logbook-card/issues/123#issuecomment-2171818036

Tried with the built-in `logbook` card, it works properly:
```
type: custom:auto-entities
card:
  type: logbook
filter:
  include:
    - group: group.motion_area_living
```
![image](https://github.com/user-attachments/assets/78c87566-30cf-4283-a624-fa42264387c5)

**Comment by ildar170975** [comment]
My test.
Create a new view, place 2 similar cards:
```
type: custom:auto-entities
card:
  type: custom:multiple-logbook-card
  hours_to_show: 1
filter:
  include:
    - entity_id: device_tracker.ac*
```
```
type: vertical-stack
cards:
  - type: custom:auto-entities
    card:
      type: custom:multiple-logbook-card
      hours_to_show: 1
    filter:
      include:
        - entity_id: device_tracker.ac*
```
i.e this is same card - but the 2nd one is placed inside `vertical-stack`.
Should be displayed as
![изображение](https://github.com/user-attachments/assets/5b9ce6f4-f210-4cfe-87fd-ebffba5e212f)

If the 1st card is shown in UI editor - no issues:
![изображение](https://github.com/user-attachments/assets/66f1dbb0-bd0f-413d-8e9b-e30207771df0)

In case of the 2nd card it is not shown & there is an error "Please define at least one entity" in console:
![изображение](https://github.com/user-attachments/assets/ced1065d-4c1c-479c-a5bd-74fe98dfc0ba)

**Comment by clau-bucur** [comment]
@royto any clue on how to fix this?

**Comment by royto** [comment]
it's a weird behaviour ...

I found a workaround that seems to work (adding an entity and then exclude it ...)

Not sure it is a bug on logbook card or auto-entities ...

```yaml
type: vertical-stack
cards:
  - type: custom:auto-entities
    card:
      type: custom:multiple-logbook-card
      hours_to_show: 1
      entities: 
        - sun.sun
    filter:
      include:
        - entity_id: device_tracker.ac*
      exclude:
        - entity_id: sun.sun
```

**Comment by clau-bucur** [comment]
It doesn't seem to be working for me.
Neither two of these examples show any card.
The referenced groups are valid and contain entities which are included in the recorder.

```
type: custom:auto-entities
card:
  type: entities
  entities:
    - sun.sun
filter:
  include:
    - group: group.door_window_area_living
    - group: group.light_area_living
    - group: group.motion_area_living
  exclude:
    - entity_id: sun.sun
```

```
type: vertical-stack
cards:
  - type: custom:auto-entities
    card:
      type: entities
      entities:
        - sun.sun
    filter:
      include:
        - group: group.door_window_area_living
        - group: group.light_area_living
        - group: group.motion_area_living
      exclude:
        - entity_id: sun.sun
```
