### ISSUE TITLE
"date_format": not using a default system HA format

### ISSUE THREAD

**Issue by ildar170975** [royto/logbook-card#129]
**Describe the bug**
According to Docs:
![изображение](https://github.com/user-attachments/assets/17765dab-9c0c-4a84-8102-848d70709c3e)
i.e. a default time format is supposed to be used.
My system format is
![изображение](https://github.com/user-attachments/assets/0d99fd8d-960f-4332-a3d9-1becf1acbbb5)

But a default time format seems to be using "AM/PM":
![изображение](https://github.com/user-attachments/assets/14b8871e-401f-49ab-bab6-0c9945e5db50)
```
type: custom:logbook-card
entity: sun.sun
```

Similarly, if an attribute is a `timestamp`:
![изображение](https://github.com/user-attachments/assets/7ee4014b-5dd7-4a39-894b-a7b20f7b466f)

then it is shown in a proper system format only if no `type: date` option specified:
![изображение](https://github.com/user-attachments/assets/f294ad4e-6dbc-487c-9c44-a7aabfcfd87a)
```
type: custom:logbook-card
entity: binary_sensor.battery_charging_ipad_air_2
attributes:
  - value: last_seen
  - value: last_seen
    type: date
    label: 'type: date'
```
and with `type: date` option is is shown in "AM/PM" format.

**To Reproduce**
see above

**Expected behavior**
A default date/time format should be as defined in HA system settings.

**Screenshots**
see above

**Environment (please complete the following information):**
 - HA Version: 2024.7.1
 - Browser: Chrome 126.0.6478.127 
 - Card version: 2.5.5

**Card configuration**
see above

**Additional context**
