### ISSUE TITLE
Attributes in Multiple logbook card

### ISSUE THREAD

**Issue by rononline** [royto/logbook-card#136]
If I use the logbook card:

```
  - type: custom:logbook-card
    desc: true
    entity: sensor.p2000_barendrecht
    title: " "
    attributes:
      - value: tekstmelding
        label: " "
    show:
      state: false
      duration: false
      start_date: true
      end_date: false
      icon: true
      separator: true
    hours_to_show: 24
    ```
 The attribute "tekstmelding" is nicely displayed.
 
But is i do it with multiple entities (all 3 same format), then it doesn't work.

```
    type: custom:multiple-logbook-card
    desc: true
    show:
      state: false
      duration: false
      start_date: true
      end_date: false
      icon: true
      separator: true
      entity_name: false
    entities:
      - entity: sensor.brandweer_barendrecht
        attributes:
          - name: tekstmelding
      - entity: sensor.politie_barendrecht
        attributes:
          - name: tekstmelding
      - entity: sensor.ambulance_barendrecht
        attributes:
          - name: tekstmelding
      ```
      
Or am I doing it wrong?
