### ISSUE TITLE
any way to display both relative and actual time of event?

### ISSUE THREAD

**Issue by stepir** [royto/logbook-card#139]
Hi I'm using this code:

```
type: custom:multiple-logbook-card
square: false
history: 3
group_by_day: true
date_format: relative
show:
  state: false
  duration: false
  start_date: true
  end_date: false
  icon: true
  separator: false
  entity_name: true
desc: true
entities:
  - entity: binary_sensor.stx_line_crossing_1
    label: Front
    hidden_state:
      - "off"
  - entity: binary_sensor.stx_line_crossing_2
    label: Left
    hidden_state:
      - "off"
  - entity: binary_sensor.stx_line_crossing_3
    label: Right
    hidden_state:
      - "off"
  - entity: binary_sensor.stx_line_crossing_4
    label: Rear
    hidden_state:
      - "off"
title: Line Crossing Events
```

which actually produce this

![Image](https://github.com/user-attachments/assets/ac92966c-c50f-433d-9a3a-b4d53ac53896)

I would find handy having also the actual time when the event was triggered but I can only either use relative `date_format` or not - is there any way around that i'm missing? thanks
