### ISSUE TITLE
Logbook for entity types

### ISSUE THREAD

**Issue by templeowls21** [royto/logbook-card#141]
Sorry if I missed this in the documentation...is there a way to have it show all entities of a certain type? LIke all light entities, cover entities, etc.? Rather than specifying each individual entity?

**Comment by royto** [comment]
Hello, this is not built in in the card but you can use [auto-entites](https://github.com/thomasloven/lovelace-auto-entities) for that

```yaml
type: custom:auto-entities
card:
  type: custom:multiple-logbook-card
  hours_to_show: 1
filter:
  include:
    - domain: light
```
