### ISSUE TITLE
custom log map - hide message

### ISSUE THREAD

**Issue by szat688** [royto/logbook-card#144]
**Describe the solution you'd like**
I can select the right custom log by name or message, but the message is too long. I wish I could simple hide it and only show the name.

**Describe alternatives you've considered**
```
custom_log_map:
  - message: 'triggered by mqtt topic zigbee2mqtt/miniswitch_doorbell/action'
    icon: 'mdi:bell'
    hide_message: true
```
