### ISSUE TITLE
Using attribute value in state_map

### ISSUE THREAD

**Issue by stancubed** [royto/logbook-card#146]
I would love to be able to map the state value so that the label is an attribute. The top row of each entry isn't always the most helpful information. My states are "on", "off", or "unknown" but the attributes (instructor, title, etc.) are very helpful.

**Describe the solution you'd like**
In my entity, the state value "on" isn't helpful but I'd like the top row of the entry in the card to display an attribute of the state instead. Something like this, maybe?
```yaml
type: custom:logbook-card
entity: sensor.peloton_workout_details_history
hidden_state:
  - unavailable
  - "off"
state_map:
  - value: "on"
    label:
      attribute: instructor
show:
  state: true
  duration: false
  start_date: true
  end_date: false
  icon: true
  separator: true
  entity_name: false
attributes:
  - value: title
custom_logs: false
```
