### ISSUE TITLE
Add the word 'ago'

### ISSUE THREAD

**Issue by iptvcld** [royto/logbook-card#15]
so i have times in my entity and it just says 35m (which was the last time this showed) - would be nice for it to say 35m ago

**Comment by JPM-git** [comment]
Time sensor's are, like the name say, time, so you what to change a sensor that shows time just because you have a specific usage?

**Comment by iptvcld** [comment]
So this is what I was talking about. The first log is using a different custom card.
![Screenshot_20200324-092939](https://user-images.githubusercontent.com/34818686/77430855-3809e400-6db2-11ea-812b-27c48cd78036.jpg)

**Comment by royto** [comment]
I will add the possibility to set custom label. It has the advantage to be more configurable and supports localization

Default value will still remain what it is now but it will be overridable by configuration

```yaml
duration_labels:
  seconds: '${value} seconds ago'
  minutes: '${value} minutes ago'
  hours:   '${value} hours ago'
  days:    '${value} days ago'
```

What do you think ?
