### ISSUE TITLE
Icon now showing

### ISSUE THREAD

**Issue by SeLLeRoNe** [royto/logbook-card#26]
Hi,
I was trying to add the icon next to the entry but it doesn't appear no matter what I do, this is my code:

```
          - type: custom:logbook-card
            title: "PIR - Patio"
            entity: binary_sensor.patio_pir
            max_items: 5
            date_format: dd/MM/YYYY hh:mm
            state_map:
              - label: Motion Detected
                value: "on"
                icon: 'mdi:run'
              - label: No Motion Detected
                value: "off"
                icon: 'mdi:walk'
            show:
              state: true
              duration: true
              end_date: false
              start_date: true
              icon: true
              separator: true
            hiddenState:
              - No Motion Detected

```

This is the outcome:
![image](https://user-images.githubusercontent.com/9599441/81495969-73099d80-92b4-11ea-8a62-33c6099309c0.png)
