### ISSUE TITLE
Group by time period

### ISSUE THREAD

**Issue by triblondon** [royto/logbook-card#32]
In a number of use cases it's helpful to identify time periods (often days) and show all the log events that occur during each period.

Use case 1: visitor log

Time periods are simply all day every day.

```
# Visitors

## Yesterday
Andrew                          14:15 - 17:23 (3hrs 7 mins)
Andrew                          08:00 - 08:14 (14 mins)
Jane                            Present all day

## Wednesday
Andrew                          14:15 - 17:23 (3hrs 7 mins)
```

Use case 2: Gym log / Swim practice etc

Time periods are days when I should go to the gym (eg Mon, Wed, Fri):

```
# Did you get your gym session in?

## Friday
Gym                  45min

## Wednesday
No matching events

## Monday
Gym                  1hr 20min
```

This idea is similar to the way that Outlook / Google Drive groups documents into 'Today', 'Yesterday', 'Last week', 'Last month', but for repeating time periods.

### Add a group_by_date_format config option

```
group_by_date_format: dddd D MMM
```

This would enable use case 1 above but would not allow you to have 'periods of interest' that are not contiguous.

### Add options for repeating events

```
time_periods:
  - name_format: dddd D MMM
    start_cron: 0 0 * * 1
    duration: 86400
  - name_format: dddd D MMM
    start_cron: 0 0 * * 3
    duration: 86400
  - name_format: dddd D MMM
    start_cron: 0 0 * * 5
    duration: 86400
```

This one allows Mondays, Wednesdays and Fridays to be isolated as periods of interest
