### ISSUE TITLE
Any way to change color for date-time range?

### ISSUE THREAD

**Issue by mkanet** [royto/logbook-card#37]
Thank you for making such a useful custom card!  If it's not too much trouble, could you please consider adding support to colorize the **date-time range** just like we can with the separator?  I think it would really make a significant improvement in readability.  

![example](https://user-images.githubusercontent.com/811008/98879215-d6c67c00-2439-11eb-83cd-8813cebce82c.png)

**Comment by emufan** [comment]
You can use cardmod with e.g.

`card_mod:`
`  style: |`
`    .date {`
`      color: var(--secondary-text-color);`
`    }`

**Comment by mkanet** [comment]
Thanks @emufan .  Where do I insert that piece of code?  Below, is the current code I have for my card.  I wasn't able to get it to change the date-time range.

```
entity: sensor.sm_a505u_last_notification
max_items: 10
hiddenState:
  - ''
collapse: 5
title: Alina - Notifications
show:
  separator: true
separator_style:
  color: '#5B5048'
  style: dashed
type: 'custom:logbook-card'
```
