### ISSUE TITLE
Unable to display attribute

### ISSUE THREAD

**Issue by gulli1986** [royto/logbook-card#44]
I have an entity attribute (named 'vehicles') that looks like this (plate recognizer integration):

```
- vehicles:
  - plate: XXXXX
    confidence: 0.9
    region_code: gb
    vehicle_type: Sedan
```
Here is what the logbook-card is showing:
![Capture](https://user-images.githubusercontent.com/84970544/132327304-c5ac69b0-dee7-4d57-b4dc-c546106638de.JPG)

And here is how I configured the card:

```
      - type: custom:logbook-card
        entity: image_processing.platerecognizer_driveway
        history: 1
        max_items: -1
        title: Latest plates recognized (last 24h)
        show:
          state: true
          duration: false
          start_date: true
          end_date: false
          icon: true
          separator: true
        attributes:
          - value: vehicles
```

Is there a way to display the vehicles attributes with all of its values?

Thanks.

**Comment by royto** [comment]
Can you try with 

```
   attributes:
          - value: vehicles.plate
```

What do you expect ? that all vehicules props are rendered ?

**Comment by royto** [comment]
find way to test this. 
My suggestion does not work.
Will try to fix this soon

**Comment by gulli1986** [comment]
@royto , thanks!
I can mention that I tried both:

```
attributes:
          - value: vehicles.plate
```

and 

```
attributes:
          - value: vehicles['plate']
```

But it didn't help.

**Comment by royto** [comment]
Should be fixed in 1.4.1

**Comment by gulli1986** [comment]
Hello @royto, thanks for you looking at it.
I updated to 1.4.1, however I still cannot display all of the vehicle attribute:

Config:
```
      - type: custom:logbook-card
        entity: image_processing.platerecognizer_driveway
        history: 1
        max_items: -1
        title: Latest plate recognized - history
        show:
          state: true
          duration: false
          start_date: true
          end_date: false
          icon: true
          separator: true
        attributes:
          - value: vehicles
```

Entity (image_processing.platerecognizer_driveway):
```
last_detection: 2021-09-08_16-53-14
vehicles:
  - plate: AB12345
     confidence: 0.902
     region_code: gb
     vehicle_type: Sedan
orientation: []
statistics:
  total_calls: 2500
  usage:
    year: 2021
    month: 9
    resets_on: '2021-09-10T23:59:43.752029Z'
    calls: 143
  calls_remaining: 2357
save_file_folder: /config/www/platerecognizer
save_timestamped_file: true
always_save_latest_file: false
unit_of_measurement: plate
friendly_name: platerecognizer_driveway
```

Lovelace:
![Capture](https://user-images.githubusercontent.com/84970544/132636716-f10480d4-6b90-4f5d-8890-4c2fff698d4f.JPG)
