### ISSUE TITLE
t.split is not a function error

### ISSUE THREAD

**Issue by ctcoder5** [royto/logbook-card#49]
I must be doing some incorrect setup on this card for hiddenState. It does not appear to be recognizing my yaml array below. I get the same error when I uncomment out the state_map below. If I change the - on to something like - true, it does not give an error but also does not hide the entity state. What seems to be the problem? I am trying to show only the 'on' states of a hue motion detector.
config:
```
title: Home
views:
  - path: default_view
    title: Home
    cards:
      - type: 'custom:logbook-card'
        desc: true
        entity: binary_sensor.hue_outdoor_motion_sensor_1_motion
        hiddenState:
          - on
        title: Garage Door Motion Sensor
        # state_map:
        #  - label: Motion
        #    value: on
        history: 1
        show:
          separator: true
```        

error text:
```
t.split is not a function
type: custom:logbook-card
desc: true
entity: binary_sensor.hue_outdoor_motion_sensor_1_motion
hiddenState:
  - true
title: Garage Door Motion Sensor
history: 1
show:
  separator: true
```

**Comment by royto** [comment]
I tried with this configuration and i got no error :

```yaml
type: custom:logbook-card
desc: true
entity: binary_sensor.detecteur_mouvement_escalier_occupancy
hiddenState:
  - 'on'
state_map:
  - label: 'No motion detected'
    value: 'off'
title:  Garage Door Motion Sensor
history: 1
show:
  separator: true

```

The Map state should not include value that are hidden because ... they are hidden
