### ISSUE TITLE
Change Date and Duration font size

### ISSUE THREAD

**Issue by ctcoder5** [royto/logbook-card#51]
Has anyone messed with increasing the font size on the date and duration text? I find it hard to read especially on my phone. I noticed some styles in the logbook-card.js, but changing those did not appear to have an affect. Can I not update the logbook-card.js file on home assistant or would I need to pull down the repo and rebuild after changes?

**Comment by royto** [comment]
You can use [mod-card](https://github.com/thomasloven/lovelace-card-mod) for this

once installed you can apply style for card elements with `style` attribute in the card configuration  

something like this

```yaml
entity: sensor.my_sensor
max_items: 10
hiddenState:
  - ''
show:
  separator: true
separator_style:
  color: '#5B5048'
  style: dashed
type: 'custom:logbook-card'
style: |
  .attribute {
    font-size: 12px;
  }
```
