### ISSUE TITLE
Card throws "Uncaught (in promise)" and does not appear

### ISSUE THREAD

**Issue by amaximus** [royto/logbook-card#52]
HASS Core 2022.6.1

The below basic configuration throws the error from the screenshot.
```
      - type: entities
        entities:
          - sensor.current_version
      - type: 'custom:logbook-card'
        desc: true
        entity: input_text.last_alarm_message
        history: 2
```
![capture_06032022_180628](https://user-images.githubusercontent.com/2511168/171904002-3e1f6e7f-ddb4-4886-8a31-aa873f3f5aab.jpg)
