### ISSUE TITLE
Collapsible doesn't show all entities?

### ISSUE THREAD

**Issue by Protoncek** [royto/logbook-card#63]
Hello!
I have internet radio and i use this great card for showing history of songs played on set station (received via DAB radio).
But, i found a couple of errors:
I have set number of days to 1. Then, there's a few funny things:
- if i set max items to "-1" and i enter in "collapse" field anything but empty i get an error "collapse must be greater than max-items".
- if i have max items to, say "1000": 
   - if i have collapse empty i correctly get all songs for last 24 hours - one day (although it would be better to have just entities from 00:00 to current time = today, but that's another thing). 
   - But, if i enter any value into collapse i get only entries for last hour, not for 24 hours when i click on "down" arrow to expand.
   - 
Am i doing anything wrong? 
Thanks!

Best regards, Pavel

**Comment by Protoncek** [comment]
Thanks a lot for correction - first point now works - error is gone. 
However, my second point is still happening... after expanding list there are only items for last hour (even if i set items to "-1", which means "all items").

**Comment by royto** [comment]
Can you provide me your configuration ?
If you don't set `collapsible`, all entry are displayed ?

**Comment by Protoncek** [comment]
Here is my config with collapsible:
```
type: custom:logbook-card
desc: true
entity: sensor.trenutna_pesem
title: Zgodovina pesmi
show:
  state: true
  duration: true
  start_date: true
  end_date: false
  icon: false
  separator: false
history: 1
no_event: ni podatkov
max_items: 1000
collapse: 6
```
with this config i only see entries for appr. last hour. now i counted songs: it appears that 20 are displayed (appr. lentgh if song is 3 mins) - beside that 6 which always appear.
But as soon as i delete entry in "collapse" i get full history for one day (so in this case last entry is yesterday 16:14).
