### ISSUE TITLE
hidden_state attribute

### ISSUE THREAD

**Issue by dimmuboy** [royto/logbook-card#65]
Is possible to implement hiding of entries based on attribute? I would like to hide entries if specific attribute is Null.

**Comment by royto** [comment]
So whatever the state is, if the entity attribute has a value, the log is hidden. right ?

**Comment by dimmuboy** [comment]
I have Steam and Discord sensors and I would like to see only if attribute **Game** is something.
I just want to filter out these empty states without any game:
![image](https://user-images.githubusercontent.com/12607479/229319477-64c47cc9-3a0c-4526-9363-7c03c01319bb.png)

**Comment by dimmuboy** [comment]
Both are true. In Discord sensor it's null but in Steam doesn't present. But I will check once again because Steam probably doesn't works due to that so just Discord with null value is in the game.

**Comment by royto** [comment]
New version 1.10.0 released with ability to filter based on attributes. Can you check it ?

**Comment by dimmuboy** [comment]
Sorry, I'm late. It works absolutely perfectly! Thank you

```yaml
type: custom:logbook-card
entity: sensor.steam_7656***
hidden_state:
  - state: away
  - attribute:
      name: game
      value: ''
      hideIfMissing: true
attributes:
  - value: game
.
.
.
```
