### ISSUE TITLE
duration_labels not working

### ISSUE THREAD

**Issue by triplecillas** [royto/logbook-card#70]
I have a just star using your excellent card, but when I try to change the duration labels, it doesn't work.

This is my card configuration:
```
type: custom:logbook-card
entity: switch.valve_1
desc: true
max_items: 1
show:
  state: false
  duration: true
  start_date: true
  end_date: false
  icon: false
  separator: false
hidden_state:
  - 'off'
title: ' '
date_format: dddd d MMM
duration:
  units:
    - h
    - m
    - s
  duration_labels:
    second: seg
    minute: min
```
An this is the result:
![Captura de pantalla 2023-06-02 a las 13 17 19](https://github.com/royto/logbook-card/assets/83791798/d09eefb3-b2d9-4995-a244-c516b326ddf9)

My expected result is "min" instead of "minutos".

What is wrong in my configuration?

**Comment by royto** [comment]
Hello, 

the property is `labels` and not `duration_labels` (see [duration configuration](https://github.com/royto/logbook-card#duration-object))

Should work with

```yaml
type: custom:logbook-card
entity: switch.valve_1
desc: true
max_items: 1
show:
  state: false
  duration: true
  start_date: true
  end_date: false
  icon: false
  separator: false
hidden_state:
  - 'off'
title: ' '
date_format: dddd d MMM
duration:
  units:
    - h
    - m
    - s
  labels:
    second: seg
    minute: min
```
