### ISSUE TITLE
minimal_duration not working

### ISSUE THREAD

**Issue by criticallimit** [royto/logbook-card#72]
Tried to use "minimal_duration" option. 
No matter where I place it, it´s ignored.

```
type: custom:logbook-card
theme: Dirk
entity: sensor.eva_ipad_browser_path
title: ' '
desc: true
history: 20
minimal_duration: 2
hidden_state:
  - unknown
  - /1-2
state_map:
  - label: Eva ist offline
    value: unavailable
    icon: mdi:sleep
    minimal_duration: 2
  - label: Eva guckt alle Cams
    value: /1-2/alle
    minimal_duration: 2
  - label: Eva guckt auf die Übersicht
    value: /1-2/uebersicht
    minimal_duration: 2
  - label: Eva guckt Cam Mo
    value: /1-2/mo
    minimal_duration: 2
  - label: Eva guckt Cam Essen
    value: /1-2/essen
    minimal_duration: 2
  - label: Eva guckt Cam Wohnen
    value: /1-2/wohnen
    minimal_duration: 2
  - label: Eva guckt Cam Küche
    value: /1-2/kueche
    minimal_duration: 2
  - label: Eva guckt auf die Map
    value: /1-2/map
    icon: mdi:map-legend
    minimal_duration: 2
show:
  state: true
  duration: true
  start_date: true
  end_date: false
  icon: true
  separator: true
  minimal_duration: 2
```

![Bildschirmfoto](https://github.com/royto/logbook-card/assets/5613811/783426d8-780e-4aa3-83ba-e172b6d58578)

entries less than 2 seconds should be ignored, but they are shown in the card

**Comment by royto** [comment]
`minimal_duration` config should be placed at the root level of the configuration like
```yaml
type: custom:logbook-card
theme: Dirk
entity: sensor.eva_ipad_browser_path
title: ' '
desc: true
history: 20
minimal_duration: 2
hidden_state:
  - unknown
  - /1-2
state_map:
  - label: Eva ist offline
    value: unavailable
    icon: mdi:sleep
  - label: Eva guckt alle Cams
    value: /1-2/alle
  - label: Eva guckt auf die Übersicht
    value: /1-2/uebersicht
  - label: Eva guckt Cam Mo
    value: /1-2/mo
  - label: Eva guckt Cam Essen
    value: /1-2/essen
  - label: Eva guckt Cam Wohnen
    value: /1-2/wohnen
  - label: Eva guckt Cam Küche
    value: /1-2/kueche
  - label: Eva guckt auf die Map
    value: /1-2/map
    icon: mdi:map-legend
show:
  state: true
  duration: true
  start_date: true
  end_date: false
  icon: true
  separator: true
```

it has been introduce in v1.11.0. 

Can you ensure that you are using the last version of the card ? 

You can see the version in the developer tools console 

![image](https://github.com/royto/logbook-card/assets/6990995/420c65fc-adcb-4a70-b20b-fa2d870fd12b)

**Comment by criticallimit** [comment]
Yes, I know that it should be in the root level. I placed it there, but placed it anywhere else as it seems to be not working.
Installed again the card via HACS a few minutes ago. No changes.
Don´t know how to proof if the actual version is installed (where I can find developer tools console?)

```
type: custom:logbook-card
theme: Dirk
entity: sensor.eva_ipad_browser_path
title: ' '
desc: true
history: 20
minimal_duration: 2
hidden_state:
  - unknown
  - /1-2
state_map:
  - label: Eva ist offline
    value: unavailable
    icon: mdi:sleep
  - label: Eva schaut auf alle Cams
    value: /1-2/alle
  - label: Eva schaut auf die Übersicht
    value: /1-2/uebersicht
    icon: mdi:list-box-outline
  - label: Eva betrachtet Cam Mo
    value: /1-2/mo
  - label: Eva betrachtet Cam Essen
    value: /1-2/essen
  - label: Eva betrachtet Cam Wohnen
    value: /1-2/wohnen
  - label: Eva betrachtet Cam Küche
    value: /1-2/kueche
  - label: Eva schaut auf die Map
    value: /1-2/map
    icon: mdi:map-legend
show:
  state: true
  duration: true
  start_date: true
  end_date: false
  icon: true
  separator: true
```

But what I can see is, that "minimal_duration" is green (as in your post), but the value "2" is not blue.
Don´t know how to add a code snippet here with colours.
