### ISSUE TITLE
History (number of days) doesn't show the correct log entries

### ISSUE THREAD

**Issue by mstuij** [royto/logbook-card#78]
The option History to show that number of days is not correct.

Set the history option to 1 you see the entries of the last 24 hours (27 oct and 26 oct):

![image](https://github.com/royto/logbook-card/assets/75884924/b1908a98-cf2c-4a49-bc73-44810fca1e85)

Set the history option to 2. Now you dont see the entries of today (27 oct) anymore:
![image](https://github.com/royto/logbook-card/assets/75884924/b3fe0a4b-aa64-4c03-a447-77923795f8cf)

Also there is an entry at the bottom: Unknown. That item should not be visible.

![image](https://github.com/royto/logbook-card/assets/75884924/f245eed0-e89b-4926-b77a-832a3c1b8a4b)

I have created dummy entities to log all my automations. The config of such a dummy entity looks like this:

```
input_button:
  automation_covers_log_entity:
    name: Automation covers log
    icon: mdi:window-shutter       

```
