### ISSUE TITLE
Add an option to show the message below the name (with a custom log)

### ISSUE THREAD

**Issue by mstuij** [royto/logbook-card#80]
The current behaviour is that you see:

{name of entity} - {message}

![image](https://github.com/royto/logbook-card/assets/75884924/94797347-bc69-4078-8843-6061e88326a4)

What I like to see is that it will presented on 2 lines, so in this example:

Rolluiken westkant
Rolluiken westkant geopend

**Comment by royto** [comment]
Currently, it is the name and the message that are displayed

![image](https://github.com/royto/logbook-card/assets/6990995/000b855a-bb15-4f70-a2e8-5c38607a9ae8)

Maybe name use entity firandly name is not set

**Comment by mstuij** [comment]
When I execute this:

![image](https://github.com/royto/logbook-card/assets/75884924/87bdd3dc-0a2a-40be-aab5-3d8d2ba8236b)


You get this:

![image](https://github.com/royto/logbook-card/assets/75884924/a83868c9-c399-4ef7-9c01-cd4a466d1c1d)


And I like to see (with a new option)

This is subject
This is the message

**Comment by royto** [comment]
Just to be clear,  you want something like this (with he date)

![image](https://github.com/royto/logbook-card/assets/6990995/0a86bfcf-7e68-4e61-b437-f9f646893b53)

**Comment by mstuij** [comment]
Yes the the 2 lines.
The date like the functionality that now already exists. 

But I have created another issue to have a group date seperator (like the original logbook card)

And it would be a great bonus if you can specify the styling. So in my case I should set the subject to bold and the message to italic.

**Comment by royto** [comment]
Hi, 

you can achieve this using [card mod](https://github.com/thomasloven/lovelace-card-mod) 

As describe in the [README.md](https://github.com/royto/logbook-card/tree/2.1.0#custom-styling), you can use the following configuration

```yaml
type: custom:logbook-card
entity: light.living_room
card_mod:
  style: |
    .custom-log .item-content {
      display: flex;
      flex-direction: column;
    }
    .custom-log .custom-log__separator {
        display: none;
    }
    .custom-log .item-content .custom-log__name {
        font-weight: bold;
    }
    .custom-log .item-content .custom-log__message {
       font-style: italic;
       text-indent: 0px;
    }
```
