### ISSUE TITLE
Unknown with custom log

### ISSUE THREAD

**Issue by alphasixtyfive** [royto/logbook-card#85]
**Describe the bug**

For some reason I'm getting a single "Unknown" entry whenever 

![image](https://github.com/royto/logbook-card/assets/55880648/7026d415-7fa3-4f3d-a45d-8f938a968d98)

Although default logbook card displays it just fine:

![image](https://github.com/royto/logbook-card/assets/55880648/20f1eecf-0108-4fce-adf5-c0ba8c72565b)

**Card configuration**
```
type: custom:logbook-card
entity: input_button.logbook_tasker
custom_logs: true

```

```
- alias: Tasker event receiver log
  trigger:
    - platform: event
      event_type: "tasker"
  action:
    - alias: Make a log entry
      service: logbook.log
      data:
        name: "{{ trigger.event.data.app }}"
        message: "{{ trigger.event.data.message }}"
        entity_id: input_button.logbook_tasker

```

**Comment by royto** [comment]
Add `show_history`: false to your config this issue.

```yaml
type: custom:logbook-card
entity: input_button.logbook_tasker
custom_logs: true
show_history: false
```

I'll update documentation to clarify this
