### ISSUE TITLE
Add support for choosing custom icons with a custom log based on the name or description

### ISSUE THREAD

**Issue by mstuij** [royto/logbook-card#88]
It should be very nice when it is possible to show custom icons in the logbook card for custom logs.

With the log service you specificy a name and message. So for example:

name = Covers open
description = Covers at the south side are opened

it would be nice if you could specifiy (the same as state_map construction) that when the name or description contains a specific text (for example covers open) value that then a specific icon should be showed.
So in the case above the open cover icon.

**Comment by mstuij** [comment]
I'm trying to use wild cards. But what is the syntax exactly?

```
  - entity: input_button.automation_covers_log_entity
    custom_logs: true
    show_history: false
    hidden_state:
      - unknown
    custom_log_map:
      - message: "%geopend%"
        icon: mdi:window-shutter-open

```
