### ISSUE TITLE
Consider value of an atribute instead of entity state

### ISSUE THREAD

**Issue by zelial** [royto/logbook-card#90]
I have a climate entity which is set to state 'auto' all the time. But when it starts to heat its 'hvac_action' attribute gets set to heating. I'd like to see the intervals of it being turned on (=heating) in the card, but because the state itself never changes, nolog entries are shown.

**Describe the solution you'd like**
Allow setting an attribute (attributes?) and its values as the deciding factor for showing/not showing a log entry.

**Describe alternatives you've considered**
Attributes can we used to provide additional info for log entries that do get displayed and and can be used to further filter out (hide) log entries that would have been shown, but AFAIK can't be used to trigger the displaying of a log entry.

**Comment by royto** [comment]
Have you considered the creation of a sensor from the climate entity based on this attribute ?

You can do it using yaml with a template something like 

```yaml
template:
  - sensor:
    - name: climate_mode #name it like you want ...
      #replace `my_climate` by your entity name 
      state: "{{ state_attr('climate.my_climate', 'hvac_action') }}" 
      unique_id: c0b35ff264f5d00dfbcf135fd560e375
```

or directly from the UI

![image](https://github.com/royto/logbook-card/assets/6990995/25f5309f-5901-47eb-96a6-2064191adfd8)
