### ISSUE TITLE
Automation triggers not showed

### ISSUE THREAD

**Issue by L0bit0** [royto/logbook-card#91]
Hi

I configured a card to show different entities logs, one of them is an automation.
If I do the same with the standard log card, i see when the automation was launched.
here you have side by side:
![image](https://github.com/royto/logbook-card/assets/10359623/64125307-82ca-4f45-a12a-7e969fe3dd19)

and the code:
```
type: logbook
entities:
  - automation.alert_shelly_aerotermia_off
  - binary_sensor.aerotermia_termostato_status
  - switch.shellyaerotermia_switch
  - binary_sensor.aerotermia
```
```
type: custom:multiple-logbook-card
desc: true
entities:
  - entity: binary_sensor.aerotermia_termostato_status
  - entity: switch.shellyaerotermia_switch
  - entity: binary_sensor.aerotermia
  - entity: automation.alert_shelly_aerotermia_off
history: 1
date_format: DD-MMM hh:mm:ss
scroll: false
action: more-info
show:
  state: true
  duration: true
  start_date: true
  end_date: true
  icon: true
  separator: true
  entity_name: true
custom_logs: true
```

I am missing anything? There is a way to show automation triggers?

Thansk

**Comment by royto** [comment]
For mutli-entities, the `custom_logs: true` has to be set per entity

Can you try with this configuration

```yaml
type: custom:multiple-logbook-card
desc: true
entities:
  - entity: binary_sensor.aerotermia_termostato_status
  - entity: switch.shellyaerotermia_switch
  - entity: binary_sensor.aerotermia
  - entity: automation.alert_shelly_aerotermia_off
    custom_logs: true
history: 1
date_format: DD-MMM hh:mm:ss
scroll: false
action: more-info
show:
  state: true
  duration: true
  start_date: true
  end_date: true
  icon: true
  separator: true
  entity_name: true
```

**Comment by L0bit0** [comment]
Hi

thanks for the response, but it is not working:
![image](https://github.com/royto/logbook-card/assets/10359623/b58a2c8c-0531-47e6-8727-ade7827cbf6d)

Thanks

**Comment by royto** [comment]
Can you provide the response of the call to `/api/logbook`  (tab network in developper tools of your browser (F12)) ?

**Comment by L0bit0** [comment]
Hi

not sure if I capture correctlly, this is what i got (I use google chrome):

![image](https://github.com/royto/logbook-card/assets/10359623/ca02634f-4e20-44a9-b398-5bd46625dbe9)

This is Response tab content

```
[
    {
        "name": "ALERT - Shelly Aerotermia Off",
        "message": "triggered by state of switch.shellyaerotermia_switch",
        "source": "state of switch.shellyaerotermia_switch",
        "entity_id": "automation.alert_shelly_aerotermia_off",
        "context_id": "01HGDSY4KDMM0D52W2BPR7X9SW",
        "when": "2023-11-29T15:07:38.990412+00:00",
        "domain": "automation"
    },
    {
        "name": "ALERT - Shelly Aerotermia Off",
        "message": "triggered by state of switch.shellyaerotermia_switch",
        "source": "state of switch.shellyaerotermia_switch",
        "entity_id": "automation.alert_shelly_aerotermia_off",
        "context_id": "01HGFN6AATZGT2TGPE7A07QGJP",
        "when": "2023-11-30T08:23:12.987166+00:00",
        "domain": "automation"
    },
    {
        "name": "ALERT - Shelly Aerotermia Off",
        "message": "triggered by state of switch.shellyaerotermia_switch",
        "source": "state of switch.shellyaerotermia_switch",
        "entity_id": "automation.alert_shelly_aerotermia_off",
        "context_id": "01HGFXDC9YGEDC9E7JRX61C0FY",
        "when": "2023-11-30T10:46:52.990946+00:00",
        "domain": "automation"
    },
    {
        "name": "ALERT - Shelly Aerotermia Off",
        "message": "triggered by state of switch.shellyaerotermia_switch",
        "source": "state of switch.shellyaerotermia_switch",
        "entity_id": "automation.alert_shelly_aerotermia_off",
        "context_id": "01HGFYASPX02YMPFKD57GH4PGZ",
        "when": "2023-11-30T11:02:56.990276+00:00",
        "domain": "automation"
    },
    {
        "name": "ALERT - Shelly Aerotermia Off",
        "message": "triggered by state of switch.shellyaerotermia_switch",
        "source": "state of switch.shellyaerotermia_switch",
        "entity_id": "automation.alert_shelly_aerotermia_off",
        "context_id": "01HGFYPAVBD68VFYH4CA4988HP",
        "when": "2023-11-30T11:09:14.987630+00:00",
        "domain": "automation"
    },
    {
        "when": "2023-11-30T11:37:35.298729+00:00",
        "state": "unavailable",
        "entity_id": "automation.alert_shelly_aerotermia_off",
        "name": "ALERT - Shelly Aerotermia Off"
    },
    {
        "when": "2023-11-30T11:37:35.313002+00:00",
        "state": "on",
        "entity_id": "automation.alert_shelly_aerotermia_off",
        "name": "ALERT - Shelly Aerotermia Off"
    }
]
```


let me know if this is not what you was looking for.

thanks!

**Comment by royto** [comment]
this is exactly what I was looking for. 

Is it possible to have the automation that create the log please (as yaml)

**Comment by L0bit0** [comment]
for sure, but I need some help to do, you mean an automation to call a service? can you give more details on how to create?

thansk

**Comment by royto** [comment]
can you paste here the content of the `automation.alert_shelly_aerotermia_off` automation

**Comment by L0bit0** [comment]
Hi

her you have:
```
alias: ALERT - Shelly Aerotermia Off
description: ""
trigger:
  - platform: state
    entity_id:
      - switch.shellyaerotermia_switch
    to: unavailable
    for:
      hours: 0
      minutes: 5
      seconds: 0
  - platform: state
    entity_id:
      - switch.shellyaerotermia_switch
    to: unknown
    for:
      hours: 0
      minutes: 5
      seconds: 0
  - platform: state
    entity_id:
      - switch.shellyaerotermia_switch
    to: "off"
    for:
      hours: 0
      minutes: 5
      seconds: 0
condition:
  - condition: state
    entity_id: automation.schedule_aerotermia_on_3_00pm_to_5_00pm_v2
    state: "off"
action:
  - service: notify.mobile_app_l0bit0iphonese
    data:
      title: HA - Shelly Aerotermia
      data:
        push:
          sound:
            name: default
            critical: 1
            volume: 1
      message: Shelly aerotermia is  {{ states('switch.shellyaerotermia_switch') }}
mode: single
```


Anyway I have created a couple of new cards to compare logs just for some automations I have and any trigger action is not showed:
![image](https://github.com/royto/logbook-card/assets/10359623/252ab8f0-1c0f-476f-916b-51bbaf5577f0)
 Thanks!
