### ISSUE TITLE
hide messages from custom_logs

### ISSUE THREAD

**Issue by sVnsation** [royto/logbook-card#93]
Hello Julien,

it would be a nice feature to hide custom log entries based in the string.
Maybe as additon for the custom_log_map ?

![grafik](https://github.com/royto/logbook-card/assets/3747263/56e04151-939e-4c3d-ab94-9a52143db6f7)

```
type: custom:logbook-card
title: Waschmaschine
group_by_day: true
show:
  entity_name: false
entity: automation.notification_washing_machine
custom_logs: true
show_history: false
custom_log_map:
  - message: "*triggered*"
    icon: mdi:information-symbol
    icon_color: black
```

Thanks and best regards
