### ISSUE TITLE
Log entries not shown in the logbook when called from script which was invoked from another script

### ISSUE THREAD

**Issue by dummylabs** [royto/logbook-card#94]
First of all, your card is amazing and I really can't live without it anymore! 😄 

**Describe the bug**
I have a simple script which I'd like to reuse in my automations and scripts to capture some custom events. It works just fine when I call it from an automation or execute it directly from Administrative tools console. 

Now to the problem: if I run my script from another script, the logbook entry is being created and is visible in the **Logbook panel**, but it is not shown in the logbook card. From the **Logbook panel** perspective the only visual difference is "triggered by" statement. See screenshots below.

**To Reproduce**
The logger script:

```
alias: Save message to logbook
sequence:
  - service: logbook.log
    data:
      name: "{{ severity or 'INFO' }}"
      message: " {{ message }} "
      entity_id: input_button.dummy_logbook_entity
mode: single
```

Call it from automation (event is shown in logbook-card):
```
alias: logme
trigger: []
condition: []
action:
  - service: script.log
    data:
      message: test from automation
mode: single
```

Call it from a script (event is not shown in logbook-card)
```
alias: test_script
sequence:
  - service: script.log
    data:
      severity: INFO
      message: test from script
mode: single
```
**Expected behavior**
Logbook entries, created from a script, which was invoked from another script, are shown in the logbook-card.

**Screenshots**

Screen 1: both events are shown in the **Logbook panel**
<img width="999" alt="SCR-20231224-nemh" src="https://github.com/royto/logbook-card/assets/4209521/6954059a-9576-4aa9-a6f0-89b4a8ab99f6">

Screen 2: only one event is shown in the logbook-card (only when the script has been invoked from automation)
<img width="451" alt="SCR-20231224-neoi" src="https://github.com/royto/logbook-card/assets/4209521/67a2e781-1357-477a-b77d-587ffa04adde">

**Environment (please complete the following information):**
 - HA Version: 2023.12.3
 - Browser brave, chrome
 - Card version 2.2.0

**Card configuration**
```
type: custom:multiple-logbook-card
entities:
  - entity: input_button.dummy_logbook_entity
    show_history: false
    custom_logs: true
    custom_log_map:
      - name: INFO
        icon: mdi:information
        icon_color: '#00FF00'
      - name: ERROR
        icon: mdi:alert-circle
        icon_color: '#FF0000'
      - name: WARN
        icon: mdi:alert-octagram
        icon_color: '#FFFF00'
scroll: true
group_by_day: true
date_format: relative
show:
  entity_name: false
```
