### ISSUE TITLE
Logbook is displayed with a delay of 5 sec when nested in grid or vertical stack

### ISSUE THREAD

**Issue by mamoel666** [royto/logbook-card#95]
**Describe the bug**
When I include my custom logbook card in a vertical-stack or grid, (only) the logbook is display with a delay of about 5 sec.
As soon as I remove the container (grid or stack), everything is back to normal.
This behaviour is quite new (~4 weeks), but sadly I can't say when it started exactly.

**To Reproduce**
Just include the custom-logbook into a grid or stack.

**Expected behavior**
Same behaviour as without grid or stack.

**Environment (please complete the following information):**
 - HA Version: 2023.12.4
 - Browser: Vivaldi, Edge, Firefox
 - Card version: 2.2.0

**Card configuration**
```
type: grid
columns: 1
cards:
  - type: custom:multiple-logbook-card
    desc: true
    history: 2
    show:
      state: true
      duration: false
      start_date: true
      end_date: false
      icon: true
      separator: false
    entity_name: true
    entities:
      - entity: binary_sensor.tuya_ts0203_01_opening
```

**Additional context**
There are no errors in the log
