### ISSUE TITLE
Hidden state feature not working

### ISSUE THREAD

**Issue by rlinick** [royto/logbook-card#98]
**Describe the bug**
While attempting to use hidden_state feature to hide "closed" state entries from the log, nothing appears to change.

**To Reproduce**
See card configuration.

**Expected behavior**
All closed state entries should not be displayed.

**Screenshots**
![image](https://github.com/royto/logbook-card/assets/67890205/3759fad1-5173-46a1-aa7e-5d386f9f5748)

**Environment (please complete the following information):**
 - HA Version: [e.g. 2023.11.1]
 - Card version [e.g. 2.0.0]

**Card configuration**

```
type: custom:multiple-logbook-card
desc: true
entities:
  - entity: binary_sensor.front_door
    hidden_state:
      - closed
  - entity: binary_sensor.back_door
    hidden_state:
      - closed
title: Front Door
date_format: dd/MM hh:mm
```

**Additional context**
